### ISSUE TITLE
How to apply it on multiple columns rather than just one?

### ISSUE THREAD

**Issue by ctrivedic2b** [jmcarpenter2/swifter#10]
I'm using `pd.apply(my_func, axis=1)` to apply a function on an entire pandas row (with multiple columns, not just one). Is there an equivalent for the axis parameter in swifter? Thanks!

EDIT: There is the axis parameter but it seems to be behaving differently than in pandas apply.

**Comment by jmcarpenter2** [comment]
Hi there, thanks so much for your question!

Unfortunately, as of the current version of dask (0.18.2), they don't have support for performing an apply across a row (i.e. axis=0).  This is why swiftapplies default to axis=1. 
I'm happy to include this in the package once there is support for it in dask.

However, I will note that you shoulld be able to perform apply to multiple columns along axis=1 simply by using the standard swiftapply `df.swifter.apply(my_func)`

I hope that answers your question!

**Comment by ctrivedic2b** [comment]
Thank you for the quick response!

Doesn't axis=1 indicate that the function must be applied in a loop from first row to last row, for all columns? So to send an entire row to the function, we need to set axis=1 not axis=0.

Here's an explanation [http://jonathansoma.com/lede/foundations/classes/pandas%20columns%20and%20functions/apply-a-function-to-every-row-in-a-pandas-dataframe/](url)
and I can confirm axis=1 works for sending entire rows to the function.

If the above is true, I'm not sure why axis=1 in swifter.apply behaves like axis=0 in pd.apply.

**Comment by jmcarpenter2** [comment]
Thank you so much for explaining what you mean!

I see the issue now, and noticed a couple minor bugs in the way I was handling inputs like this. I will release a new version of swifter immediately with these fixes.

However, those fixes do not resolve the issue you are having. I have additionally [submitted a request](https://github.com/dask/dask/pull/482) to dask to include support for axis=0 applies. I will incorporate them as soon as I am able to and will leave this issue open until then.

Thanks for raising this issue and helping me improve the package!

**Comment by ctrivedic2b** [comment]
Thanks Jason, glad if I could be of any help. I'll close this issue and keep a watch of the repository to know of any developments. Keep up the good work!
