### ISSUE TITLE
Kernel dies after importing swifter

### ISSUE THREAD

**Issue by Mmoncadaisla** [jmcarpenter2/swifter#101]
Hello! 

I am experiencing an issue when trying to import swifter in Jupyter Notebook - **Kernel basically dies after importing**.

![image](https://user-images.githubusercontent.com/48254102/75243653-93a07c00-57ca-11ea-8dfc-9312b15f1ab3.png)

python version: 3.7.4
pandas version: 1.0.1
swifter version: 0.301

I'm on MacOS Mojave (v 10.14) and 8 GB RAM.

I am using Anaconda 3 and I've tried both installing via pip and via conda.

Also tried using virtualenv just in case there was any incompatibility issue but still ran into the same problem.

Thank you in advance for your attention, if you need any other details please just ask for them!

**Comment by jmcarpenter2** [comment]
Hi @Mmoncadaisla,

Sorry for the delay in my response and thanks for bringing this to my attention. I will do my best to replicate this issue in a python 3.7.4-based docker container soon and get back to you about what the issue is and what I can do to resolve this for you.

Thanks,
Jason

**Comment by Mmoncadaisla** [comment]
Hey @jmcarpenter2, 

Thank you so much for coming back to me. We're you able to reproduce it?

Is there any additional info that I can provide?

Best,

**Comment by jmcarpenter2** [comment]
Hi @Mmoncadaisla ,

Sorry for the delay, things have been pretty hectic lately due to the global crisis. I was initially unable to reproduce your issue, but I will take another look soon.

Thanks,
Jason

**Comment by Mmoncadaisla** [comment]
Hey @jmcarpenter2, I completely understand the situation and hope that all of you are doing well.

Thank you very much for working on this issue :)

**Comment by jmcarpenter2** [comment]
Hey @Mmoncadaisla ,

Can you try the following steps and see if this works?

1. [Install Docker for Mac](https://docs.docker.com/docker-for-mac/install/)
2. Pull the latest jupyter/scipy-notebook docker image 
- `docker pull jupyter/scipy-notebook`
3. Run a jupyter notebook inside the docker-container, and map the ports
- `docker run -p 8888:8888 jupyter/scipy-notebook`
4. Open up the notebook at `localhost:8888/?token=<token>`
- In the below screenshot, the <token> is `3e0aeab648c5401beaeaee4f498af0566bed2585566dd668`
![Screen Shot 2020-04-04 at 11 45 34 AM](https://user-images.githubusercontent.com/29585347/78458907-dd9e3c80-7669-11ea-9419-8befec363c6c.png)
5. Install swifter into the container by running the following command in the notebook
- `!pip install swifter`
6. Import pandas and swifter and test out an apply
![Screen Shot 2020-04-04 at 11 47 12 AM](https://user-images.githubusercontent.com/29585347/78458929-0b838100-766a-11ea-86d3-4e979732f1bc.png)

Let me know how that goes :)
Thanks,
Jason

**Comment by Mmoncadaisla** [comment]
Hey @jmcarpenter2, thank you very much for your response, I'll check it as soon as I can and update you through here :)

**Comment by Mmoncadaisla** [comment]
Hello @jmcarpenter2, first of all apologies for taking so long in order to test your proposed solution.

Downloading the docker image and importing swifter there worked as expected since I could import swifter without any issue.

Thank you very much for your time :)

**Comment by jmcarpenter2** [comment]
Happy to help @Mmoncadaisla !
