### ISSUE TITLE
What happen when you use Swifter for small dataset?

### ISSUE THREAD

**Issue by dyngts** [jmcarpenter2/swifter#11]
Hi guys, just wondering if you had done benchmarking between pandas apply, swift apply, and dask apply to perform on small dataset. is swift still superior than others? Thank you

**Comment by jmcarpenter2** [comment]
Hi there, thank you for your interest in swifter!

Please check out the swiftapply_speedcomparison.ipynb notebook in the examples folder. It uses the old formulation of swiftapply(df, func, ...) but the underlying workhorse code is the same. 

From the plots produced in that notebook we can see that on a variety of data sizes (# rows ranging from 2 to ~72million rows) swiftapply automatically converges to whichever is faster: pandas apply or dask apply.

![convergence](https://user-images.githubusercontent.com/29585347/44414594-04564080-a523-11e8-8009-d10bf0099d3c.png)

The entire purpose of swifter is to flexibly decide whether to use pandas or dask, so it is intended for datasets of any size.

**Comment by dyngts** [comment]
Thanks @jmcarpenter2, great explanation!

**Comment by jmcarpenter2** [comment]
No problem :+1:, thanks!
