### ISSUE TITLE
Module fails to load when pandas <= 0.22.x

### ISSUE THREAD

**Issue by resurrexi** [jmcarpenter2/swifter#12]
It seems that the module fails to load with pandas<=0.22.x.

The failure occurs at `@pd.api.extensions.register_series_accessor("swifter")` because `register_series_accessor` isn't found.

I did an upgrade to pandas==0.23.1 and the module was able to load successfully.

**Comment by jmcarpenter2** [comment]
Thank you for raising this point. I will make it more clear that users may need to update pandas because the pandas extensions api is a relatively new inclusion in the pandas package.
