### ISSUE TITLE
pickle5 shall not be in wheel requirement for Python>3.7

### ISSUE THREAD

**Issue by stonebig** [jmcarpenter2/swifter#122]
.I fail to install pickle5 on Windows Python-3.8+, and it shall not be asked ... unless you can provide a  wheel ?

**Comment by jmcarpenter2** [comment]
Hey @stonebig,

Thanks for flagging this issue. It looks like this dependency was unnecessary. It has been removed in swifter version `1.0.2`.

To use swifter without the pickle5 dependency please upgrade with `pip install -U swifter` or `pip install swifter==1.0.2`

Thanks again,
Jason
