### ISSUE TITLE
TypeError Thrown for Geospatial Calculations

### ISSUE THREAD

**Issue by yesthisistom** [jmcarpenter2/swifter#132]
When calling 

`df[geom_col].swifter.apply(lambda geom: geom.minimum_rotated_rectangle)`

A TypeError is thrown.  `TypeError: apply() takes from 2 to 3 positional arguments but 4 were given`

If its something simpler, like getting the area, no error is thrown 

`df[geom_col].swifter.apply(lambda geom: geom.area)`

Swifter version 0.305, Pandas version 1.1.3, dask version 2.22, geopandas version 0.8.1

Full error:

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-72fa7e94ac35> in <module>
----> 1 df[geom_col].swifter.apply(lambda geom: geom.minimum_rotated_rectangle)

C:\ProgramData\Anaconda3\lib\site-packages\swifter\swifter.py in apply(self, func, convert_dtype, args, **kwds)
    263             # if pandas sample apply takes too long and not performing str processing, use dask
    264             if (est_apply_duration > self._dask_threshold) and allow_dask_processing:
--> 265                 return self._dask_apply(func, convert_dtype, *args, **kwds)
    266             else:  # use pandas
    267                 if self._progress_bar:

C:\ProgramData\Anaconda3\lib\site-packages\swifter\swifter.py in _dask_apply(self, func, convert_dtype, *args, **kwds)
    226                     dd.from_pandas(self._obj, npartitions=self._npartitions)
    227                     .apply(lambda x: func(x, *args, **kwds), convert_dtype=convert_dtype, meta=meta)
--> 228                     .compute(scheduler=self._scheduler)
    229                 )
    230 

C:\ProgramData\Anaconda3\lib\site-packages\dask\base.py in compute(self, **kwargs)
    165         dask.base.compute
    166         """
--> 167         (result,) = compute(self, traverse=False, **kwargs)
    168         return result
    169 

C:\ProgramData\Anaconda3\lib\site-packages\dask\base.py in compute(*args, **kwargs)
    445         postcomputes.append(x.__dask_postcompute__())
    446 
--> 447     results = schedule(dsk, keys, **kwargs)
    448     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    449 

C:\ProgramData\Anaconda3\lib\site-packages\dask\multiprocessing.py in get(dsk, keys, num_workers, func_loads, func_dumps, optimize_graph, pool, **kwargs)
    216             pack_exception=pack_exception,
    217             raise_exception=reraise,
--> 218             **kwargs
    219         )
    220     finally:

C:\ProgramData\Anaconda3\lib\site-packages\dask\local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    484                         _execute_task(task, data)  # Re-execute locally
    485                     else:
--> 486                         raise_exception(exc, tb)
    487                 res, worker_id = loads(res_info)
    488                 state["cache"][key] = res

C:\ProgramData\Anaconda3\lib\site-packages\dask\local.py in reraise(exc, tb)
    314     if exc.__traceback__ is not tb:
    315         raise exc.with_traceback(tb)
--> 316     raise exc
    317 
    318 

C:\ProgramData\Anaconda3\lib\site-packages\dask\local.py in execute_task()
    220     try:
    221         task, data = loads(task_info)
--> 222         result = _execute_task(task, data)
    223         id = get_id()
    224         result = dumps((result, id))

C:\ProgramData\Anaconda3\lib\site-packages\dask\core.py in _execute_task()
    119         # temporaries by their reference count and can execute certain
    120         # operations in-place.
--> 121         return func(*(_execute_task(a, cache) for a in args))
    122     elif not ishashable(arg):
    123         return arg

C:\ProgramData\Anaconda3\lib\site-packages\dask\optimization.py in __call__()
   1020         if not len(args) == len(self.inkeys):
   1021             raise ValueError("Expected %d args, got %d" % (len(self.inkeys), len(args)))
-> 1022         return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
   1023 
   1024     def __reduce__(self):

C:\ProgramData\Anaconda3\lib\site-packages\dask\core.py in get()
    149     for key in toposort(dsk):
    150         task = dsk[key]
--> 151         result = _execute_task(task, cache)
    152         cache[key] = result
    153     result = _execute_task(out, cache)

C:\ProgramData\Anaconda3\lib\site-packages\dask\core.py in _execute_task()
    119         # temporaries by their reference count and can execute certain
    120         # operations in-place.
--> 121         return func(*(_execute_task(a, cache) for a in args))
    122     elif not ishashable(arg):
    123         return arg

C:\ProgramData\Anaconda3\lib\site-packages\dask\utils.py in apply()
     29 def apply(func, args, kwargs=None):
     30     if kwargs:
---> 31         return func(*args, **kwargs)
     32     else:
     33         return func(*args)

C:\ProgramData\Anaconda3\lib\site-packages\dask\dataframe\core.py in apply_and_enforce()
   5256     func = kwargs.pop("_func")
   5257     meta = kwargs.pop("_meta")
-> 5258     df = func(*args, **kwargs)
   5259     if is_dataframe_like(df) or is_series_like(df) or is_index_like(df):
   5260         if not len(df):

C:\ProgramData\Anaconda3\lib\site-packages\dask\utils.py in __call__()
    893 
    894     def __call__(self, obj, *args, **kwargs):
--> 895         return getattr(obj, self.method)(*args, **kwargs)
    896 
    897     def __reduce__(self):

TypeError: apply() takes from 2 to 3 positional arguments but 4 were given`

**Comment by tm2josep** [comment]
Does it produce this same error when you don't use swifter?

**Comment by jmcarpenter2** [comment]
Hi @yesthisistom,

@tm2josep 's question is an important one. First step is to check that.

Secondly, my guess is that this is related to the attribute `geom.minimum_rotated_rectangle`. Is that a tuple of 4 elements? It is possible that you need to do something like `df[geom_col].swifter.apply(lambda geom: tuple(geom.minimum_rotated_rectangle))` so that the attribute is encapsulated in a data structure, rather than being parsed into positional args for the apply function.

Thanks,
Jason

**Comment by yesthisistom** [comment]
Nope, this error first showed up when I started working with swifter. 

I got it to work row-wise on the dataframe, rather than on the series, accessing the geometry as part of the lambda function.  

Unfortunately for these operations it seems to be falling back on pandas standard apply, as I'm not seeing any speed increase.

**Comment by yesthisistom** [comment]
`df.swifter.apply(lambda geom: geom[geom_col].minimum_rotated_rectangle, axis=1)`

That works for some reason.
