### ISSUE TITLE
importing swifter hijacks logging 

### ISSUE THREAD

**Issue by gkennos** [jmcarpenter2/swifter#137]
If I am logging to console or file, just the act of importing swifter stops all logging.

I have tested this in a fresh colab with only swifter installed, and it is also the case with logging.handlers.RotatingFileHandler

MWE:
```python
import logging
import pandas as pd

logger = logging.getLogger('myapp')
logger.setLevel(logging.DEBUG)
handler = logging.StreamHandler()
formatter = '[%(levelname)s] - %(asctime)s : %(message)s'
handler.setFormatter(logging.Formatter(formatter))
logger.addHandler(handler)
logger.debug('message')
```
>>> [DEBUG] - 2020-10-22 23:00:12,202 : message

```python
pip install -q swifter
import swifter
logger.debug('message after importing swifter')
```
>>> [no output]

**Comment by jmcarpenter2** [comment]
Hi @gkennos , thanks for raising this!

This is definitely concerning. Let me look into resolving this. The original purpose of disabling logging for swifter was to avoid repeated logging during swifter's applies. See #130 for a discussion. I'll follow-up here when I have a solution.

Thanks,
Jason

**Comment by gkennos** [comment]
Issue is with this line in __init__.py: ```config.dictConfig({"version": 1, "disable_existing_loggers": True})```

Commenting that out, logging works as expected - I tested the example in #130 and it seems to work correctly with that line commented as well - don't have time to test more extensively right now, sorry, but thought I'd post anyway because it may still be helpful.

I figured it would be the 'disable_existing_loggers', so left it as ```config.dictConfig({"version": 1})```, but that still suppressed all logging.

**Comment by kanu** [comment]
An easy solution would be to let `disable_existing_loggers`  be set by an optional environment variable.

**Comment by greatvovan** [comment]
Damn, I wasted an hour trying to figure out why my logging got broken...

What is that? https://github.com/jmcarpenter2/swifter/blob/01ac2ea99e3ddaf7a3a5846ab8e0d1f96236dab1/swifter/__init__.py#L8
Why?

**Comment by jmcarpenter2** [comment]
Hey all, thanks for your patience. This is a bad bug. I will work on this shortly!

**Comment by kevhill** [comment]
With `swifter==1.0.7` it is only disrupting loggers defined before importing swifter. re-ordering my imports let me manage this.

**Comment by jmcarpenter2** [comment]
Removed the line https://github.com/jmcarpenter2/swifter/blob/01ac2ea99e3ddaf7a3a5846ab8e0d1f96236dab1/swifter/__init__.py#L8 
from `swifter==1.0.8` #156
