### ISSUE TITLE
how to shut down the process bar when using df.apply(lambda func)

### ISSUE THREAD

**Issue by skykiseki** [jmcarpenter2/swifter#138]
the process bars are annoying  when I want to use the swifter on my notebooks, especially in the scene of codes with some loops.

is there any parameters or any settings for shutting down the process bars?

**Comment by jmcarpenter2** [comment]
Hi @skykiseki ,

Please see the documentation [here](https://github.com/jmcarpenter2/swifter/blob/master/docs/documentation.md#6-pandasdataframeswifterprogress_barfalseapply)

`df.swifter.progress_bar(False).apply(...)`

Thanks,
Jason

**Comment by skykiseki** [comment]
> Hi @skykiseki ,
> 
> Please see the documentation [here](https://github.com/jmcarpenter2/swifter/blob/master/docs/documentation.md#6-pandasdataframeswifterprogress_barfalseapply)
> 
> `df.swifter.progress_bar(False).apply(...)`
> 
> Thanks,
> Jason

thanks a lot.
