### ISSUE TITLE
Swifter only using single core and no progress bar

### ISSUE THREAD

**Issue by arsalan993** [jmcarpenter2/swifter#140]
I have a data frame containing 50000 articles and I am just using the NLTK pipeline to remove stop works.
Using a later version of swifter, it was only utilizing a single core even I enable dask_on_strings(True). and no progress bar was shown.

Then I downgraded to version 1.0.0, here somehow it is consuming 30%-50% from all cores but still no progress bar is shown.

I am not using anaconda.  I have installed Jupiter notebook inside pip Virtualenv

`data2['content'] = data1['content'].swifter.progress_bar(enable=True, desc=None).allow_dask_on_strings(enable=True).apply(rem_stop_words)`

**Comment by arsalan993** [comment]
also i am using ubuntu 20, 4 cores intel CPU

**Comment by arsalan993** [comment]
Well i was able to solve half of the issue..  now i am getting full CPU consumption on all cores but still no progress bar.
Getting this inplace of progess bar

`HBox(children=(HTML(value='Dask Apply'), FloatProgress(value=0.0, max=8.0), HTML(value='')))`

**Comment by arsalan993** [comment]
Got this issue resolved as well..  u need to install nodejs and npm in ubunut incase you are not using anaconda.

**Comment by moritzschaefer** [comment]
Would you mind sharing how you solved your firts issue?
