### ISSUE TITLE
Relatively simple script runs in endless loop with errors

### ISSUE THREAD

**Issue by paberr** [jmcarpenter2/swifter#142]
First of all, thanks for building `swifter`!
I was looking to speed up computations done on large pandas DataFrames in an easy way and this looks like a good fit.

After trying to incorporate it into my project, however, I encountered an endless loop of errors.
So, I set off to build a minimal script reproducing these errors and here it is:
```python
import numpy as np
import pandas as pd
import swifter

print('Sampling data')
df = pd.DataFrame(np.random.rand(10000,50))
df = df.swifter.apply(lambda col: pd.cut(col, 5))

df_mid = df.swifter.applymap(lambda x: x.mid)

print(df_mid)
```
If you remove all occurrences of `swifter`, it works flawlessly btw.

It might be that the error here is on my side, but with using `swifter`, it produces tons of errors and also prints out `Sampling data` endlessly.

The two errors I've seen are:
1) `AttributeError: 'DataFrame' object has no attribute 'mid'` -> why is this even called in that way? (this might be related to #112)
While thinking about it, this exception is probably raised when it tries to vectorise the function.
2) and the following:
```
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```
You can probably easily reproduce the tracebacks yourself. If not, I'll happily attach them here.

Here's an excerpt of my `pip freeze`:
```
cloudpickle==1.6.0
matplotlib==3.3.3
modin==0.8.2
numpy==1.19.4
pandas==1.1.4
swifter==1.0.7
```

Thank you for your support!

**Comment by mas-dse-juremigi** [comment]
I ran into this issue. You need to put all of your code under:
`if __name__ == '__main__':`
or put it in a function and call the function after this if statement. 

```
import numpy as np
import pandas as pd
import swifter

if __name__ == '__main__':
    print('Sampling data')
    df = pd.DataFrame(np.random.rand(10000,50))
    df = df.swifter.apply(lambda col: pd.cut(col, 5))

    df_mid = df.swifter.applymap(lambda x: x.mid)

    print(df_mid)

```
