### ISSUE TITLE
Declare modin as optional please

### ISSUE THREAD

**Issue by bnavigator** [jmcarpenter2/swifter#147]
Hello,

you declare `modin[ray]` in `install_requires`, which makes it a hard requirement. The code itself however is written in a way that swifter can work without modin. Modin is not (yet) available as a package for openSUSE. Thus, the swifter package can not build right now.

Please consider marking the modin dependency as optional and make it possible to skip the unit tests involving modin if it is not installed.

**Comment by jmcarpenter2** [comment]
Hey @bnavigator , thanks for flagging this! I will fix this shortly. Optional makes a ton of sense!

**Comment by jmcarpenter2** [comment]
Resolved in swifter==1.0.8 #156

Please refer to the README on how to install swifter with modin[ray] (pip install swifter[modin-ray])
