### ISSUE TITLE
Add option to disable sampling 

### ISSUE THREAD

**Issue by juls858** [jmcarpenter2/swifter#149]
It would be great if there was a way to turn off sampling for an apply or Dask apply.  This would be useful in cases where you want to parallelize data serialization, ie to a database. 

```python
df.swifter.disable_sample().apply()
```

**Comment by jmcarpenter2** [comment]
Hey @juls858 , thanks for the great idea!

This feature is released as `force_parallel` in version `1.2.0`,

e.g. `df.swifter.force_parallel().apply()`

Please see the changelog and documentation for additional information https://github.com/jmcarpenter2/swifter/tree/master/docs
