### ISSUE TITLE
"from swifter import swiftapply" doesn't work anymore!

### ISSUE THREAD

**Issue by soumendra** [jmcarpenter2/swifter#15]
Python version: 3.6
swifter version: 0.225

    $ python
    Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
    [GCC 7.2.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import swifter
    >>> from swifter import swiftapply
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: cannot import name 'swiftapply'
    >>>

**Comment by jmcarpenter2** [comment]
Hi Soumendra,

Thanks for raising this issue for all the original swifter users.

In version 0.200 the expression for using swifter became more idiomatic.

Let's say you have some pandas dataframe

`import pandas as pd`
`df = pd.DataFrame(data=..., columns=...)`

Then using swifter is as follows
`import swifter`
`df.swifter.apply(func)`

I hope that helps!

**Comment by akaniklaus** [comment]
Hello, it is great that Swifter is becoming more idiomatic but now it doesn't work with rolling objects #27

**Comment by mikeymezher** [comment]
@jmcarpenter2 
Thanks for this! 

You should consider updating https://medium.com/@jmcarpenter2/swiftapply-automatically-efficient-pandas-apply-operations-50e1058909f9

**Comment by jmcarpenter2** [comment]
Hi @mikeymezher,

Thanks for the suggestion, that's a good idea. I just updated the medium blog post.

Best,
Jason

**Comment by rraadd88** [comment]
Hi @jmcarpenter2 ,
I just got the same error while trying out [speed benchmark notebook]( https://github.com/jmcarpenter2/swifter/blob/master/examples/swiftapply_speedcomparison.ipynb).
Probably need to update that too. 
Best,
Rohan

**Comment by jmcarpenter2** [comment]
Hi @rraadd88 , thanks for pointing this out. I am fixing up the benchmark notebook right now and the other example notebook as well. I will submit a PR later today with these updated materials.

Much appreciated,
Jason

**Comment by jmcarpenter2** [comment]
@rraadd88 just following up here..

Per PR #105 , the [speed comparison notebook](examples/swifter_speed_comparison.ipynb) is now updated to use the current syntax for swifter. I took the new plots created from the perfplot library and put those for the README as well.

Thanks again,
Jason

**Comment by Absolutorcinus** [comment]
I get this error whenever i try to apply swifter on my Dataset,
while for the following example it works:
```
#def add_squares(a,b):
#    return a**2+b**2
#df = pd.DataFrame({'X':np.random.randint(1000, size=100000),'Y':np.random.randint(1000, size=100000)})
#df ['add_sq']=df.swifter.apply(lambda row:add_squares(row.X,row.Y),axis=1)
```
**My code**
```
import swifter
import pandas as pd
import numpy as np
```

```
df = pd.read_csv('dataset.csv')
#function to return the length of the string
def letcnt(a):
    return len(a)

df['something'] = df['text'].swifter.apply(lambda x: letcnt(x))
```
Error:
-------------------------------------------------------

> Pandas Apply:   0%|          | 0/91388 [00:00<?, ?it/s]Traceback (most recent call last):
>   File "C:\Users\ii\PycharmProjects\pythonProject1\venv\lib\site-packages\swifter\swifter.py", line 258, in apply
>     & (sample_df.shape == tmp_df.shape),
> AttributeError: 'int' object has no attribute 'shape'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\ii\PycharmProjects\pythonProject1\sentiment_analisis\dataframe.py", line 11, in <module>
>     df['length_text'] = df['text'].swifter.apply(lambda x: letcnt(x))
>   File "C:\Users\ii\PycharmProjects\pythonProject1\venv\lib\site-packages\swifter\swifter.py", line 281, in apply
>     return self._obj.progress_apply(
>   File "C:\Users\ii\PycharmProjects\pythonProject1\venv\lib\site-packages\tqdm\std.py", line 754, in inner
>     func = df._is_builtin_func(func)
>   File "C:\Users\ii\PycharmProjects\pythonProject1\venv\lib\site-packages\pandas\core\generic.py", line 5478, in __getattr__
>     return object.__getattribute__(self, name)
> 
> AttributeError: 'Series' object has no attribute '_is_builtin_func'
> Pandas Apply:   0%|          | 0/91388 [00:00<?, ?it/s]
> 
> Process finished with exit code 1
