### ISSUE TITLE
Applying function to pandas series receives series instead of row with swifter

### ISSUE THREAD

**Issue by dabla** [jmcarpenter2/swifter#151]
`def split_fk_keys(desc):
            desc_split = desc.split('_')

            if len(desc_split) > 1:
                return "{}{}".format(desc_split[0], "Key")
            else:
                return desc`

This one works in plain pandas:

       `relations['column_name'].apply(split_fk_keys)`

This one doesn't work with swifter, relations['column_name'] returns a Series, and that series is passed as argument to the split_fk_keys method instead of each row in that series:

       `relations['column_name'].swifter.apply(split_fk_keys)`

Same problem when tried it this way (should make no difference as it's actually same as above):

      `relations['column_name'].swifter.apply(lambda row: split_fk_keys(row))`

Or even:

      `relations.swifter.apply(lambda row: split_fk_keys(row['column_name']))`

**Comment by malikhijazi** [comment]
Is there a workaround for this @jmcarpenter2 @dabla ? I am receiving my entire dataframe in my function when I run `df_matches_user_threshold_without_dups.apply(lambda row: less_than_threshold(row, radius, logger), axis=1)`

**Comment by malikhijazi** [comment]
Could this line https://github.com/jmcarpenter2/swifter/blob/master/swifter/swifter.py#L213 be the reason we receive the full series/dataframe. It is removing the axis keyword. Just a wild guess.

**Comment by meandmymind** [comment]
@malikhijazi i just make guard in my lambda: `df_matches_user_threshold_without_dups.swifter.apply(lambda row: less_than_threshold(row, radius, logger) if isinstance(row, Series) else False, axis=1)`

**Comment by BotScutters** [comment]
@jmcarpenter2 
Piling on here--I've been seeing this bug come up quite a bit, occurring in this chunk of `swifter.apply`:

```python
        try:  # try to vectorize
            with suppress_stdout_stderr_logging():
                tmp_df = func(sample, *args, **kwds)  # <-- THIS LINE THROWS THE ERROR
                sample_df = sample.apply(func, axis=axis, raw=raw, result_type=result_type, args=args, **kwds)
                self._validate_apply(
                    np.array_equal(sample_df, tmp_df) & (sample_df.shape == tmp_df.shape),
                    error_message="Vectorized function sample does not match pandas apply sample.",
                )
            return func(self._obj, *args, **kwds)
        except ERRORS_TO_HANDLE:  # if can't vectorize, estimate time to pandas apply
```

`sample` here is a DataFrame, and being sent into the supplied function, which is expecting a row (pd.Series).

What's interesting is that I'm only actually seeing this error crop up while I'm running the code in a debugger, not during "normal" operations. The errors that are being raised for me are either TypeError or ValueError, which it looks like you're nominally handling these errors in the try-catch block, and yet the error still gets raised.

I didn't dig too much into your `suppress_stdout_stderr_logging` function, but perhaps its something in there?

**Comment by jmcarpenter2** [comment]
Hey everyone, sorry for the (massive) delay here.. I believe there's a chance that this is related to the bug in #177 , which is going to be resolved by #179 

Once I release version `1.1.3`, I will give the all clear and I am hoping someone can check if it's resolved then on your actual data. Without data I can't really test if it works as expected (other than a local check with fake data)

**Comment by jmcarpenter2** [comment]
Didn't mean to close it. Was hoping to get some feedback from the folks here first

**Comment by dabla** [comment]
I'll test it in my spare time, currently the project is working using plain pandas without swifter.  Nice to see there is progression on this issue, good work! :)

**Comment by jmcarpenter2** [comment]
2.5 months later follow-up: haven't received any comment that it doesn't work so I am closing this issue. Please feel free to reopen if it is still broken!
