### ISSUE TITLE
Why are Assertion Error not handled

### ISSUE THREAD

**Issue by Syndorik** [jmcarpenter2/swifter#152]
I would first like to thank you for your work, this library is amazing!

I am working with a function from a library (stanza) that assert its inputs. I wanted to use swifter to parallelise the computations, however I've come to see that first the pd.Series is passed as input and then only each row is passed as input to the function.  If I understood correctly this is done to check whether or not the function can be vectorized.  Since the function that I'm using is asserting its input, an assertion error is thrown and it seems that the library don't handle assertion errors.

Here a sample code to recreate the behaviour:

```
import swifter
import pandas as pd
import re

df = pd.Series(["1", "2", "3", "4"])

def f(x):
    assert type(x) == int
    re.sub("3", "bbb", x)

df.swifter.apply(lambda k: f(k))

``` 

Because of the assertion, this does not work.

A work around that I've found:

```
import swifter
import pandas as pd
import re

df = pd.Series(["1", "2", "3", "4"])

def f(x):
    try:
        assert type(x) == int
        re.sub("3", "bbb", x)
    except Exception as e:
        raise AttributeError

df.swifter.apply(lambda k: f(k))

```

**Comment by jmcarpenter2** [comment]
If an assertion is not met.. isn't it supposed to error out?
