### ISSUE TITLE
Exception on dataframe that contains more than 16 rows

### ISSUE THREAD

**Issue by ray306** [jmcarpenter2/swifter#16]
Swifter apply works well on small dataframe, just like:
> pd.DataFrame([[1,2,3]]*16).swifter.apply(lambda x: x-np.ones(16), axis=0)

But if I increase the row number to 17, it raised:
> pd.DataFrame([[1,2,3]]*17).swifter.apply(lambda x: x-np.ones(17), axis=0)
ValueError: ('operands could not be broadcast together with shapes (16,) (17,) ', 'occurred at index 0')

**Comment by jmcarpenter2** [comment]
Hi @ray306,

Could you test the second code snippet on your machine again?`pd.DataFrame([[1,2,3]]*17).swifter.apply(lambda x: x-np.ones(17), axis=0)`

This code runs on my machine, and given your `ValueError`, my suspicion is that it was a simple error of not changing a 16 to a 17.

Furthermore, the way `swifter` is written means that for _small_ data of only 3 columns and 17 rows, swifter will default to a `pandas` apply. So I can't even think of an alternative explanation as to why this error would occur.

I hope this resolves your problem. If it does, please close this issue. Thanks!

**Comment by jmcarpenter2** [comment]
Closing this issue. Feel free to re-open it if you are still experiencing problems.
