### ISSUE TITLE
No progressbar

### ISSUE THREAD

**Issue by tbrodbeck** [jmcarpenter2/swifter#162]
Hi, I tried  a bunch of stuff, but I cannot see a progress bar when using swifter.

This is my system:
```
OS: macOS 11.4 20F71 x86_64
Host: MacBookPro16,1
Kernel: 20.5.0
Uptime: 14 days, 5 hours, 51 mins
Packages: 109 (brew)
Shell: zsh 5.8
Resolution: 3840x2160, 2048x1280
DE: Aqua
WM: Quartz Compositor
WM Theme: Blue (Light)
Terminal: iTerm2
Terminal Font: HackNerdFontCompleteM-Regular 12
CPU: Intel i7-9750H (12) @ 2.60GHz
GPU: Intel UHD Graphics 630, AMD Radeon Pro 5300M
Memory: 10164MiB / 16384MiB
```

I also tried it on ubuntu, in plain python/jupyter ...

I created this M(non-)WE that gives no output:
```py
import pandas as pd
import swifter
df = pd.DataFrame({'x': [1, 2, 3, 4], 'y': [5, 6, 7, 8]})
df.swifter.apply(lambda x: x, axis=1)
```

**Comment by jmcarpenter2** [comment]
Try a more complicated function on a larger dataset . Swifter first tries to vectorize the process, which inherently cannot provide a progress bar. Let me know if you have any trouble after trying that

**Comment by lightonphiri** [comment]
Sorry to hijack this thread, but I am experiencing a similar issue: I wonder if you managed to find a solution for this? Using Swifter without the progress bar makes it hard to ascertain if my pipeline is being executed efficiently.

**Comment by jmcarpenter2** [comment]
Closing in favor of #176
