### ISSUE TITLE
How to use pip install swifter to reproduce conda install?

### ISSUE THREAD

**Issue by ggnicolau** [jmcarpenter2/swifter#167]
Hi, I've programmed a data science app using a VM from GCP. I've installed Swifter through conda so it could decide if it's better to use ray, dask, pandas apply or vectorize. It works flawless on the VM, but now I need to put it in production. To do it, I must provide a requirements.txt to the platform, but it can't be through conda, it will install packages through pip.

But, while 'conda install -c conda-forge swifter' is one line of code, swifter provides a bunch of pip installs as it follows:
$ pip install -U pandas # upgrade pandas
$ pip install swifter # first time installation
$ pip install swifter[modin-ray] # first time installation including modin[ray]
$ pip install swifter[modin-dask] # first time installation including modin[dask]

$ pip install -U swifter # upgrade to latest version if already installed

To reproduce exactly the conda install I should run all those line of codes through pip or is it one line specifically?

**Comment by jmcarpenter2** [comment]
This should be resolved with #172 . Please give it a go and let me know if you can install for your production deployment via requirements.txt!

**Comment by jmcarpenter2** [comment]
Update: 
- I put up a pull request with conda-forge here https://github.com/conda-forge/staged-recipes/pull/17950#issuecomment-1030707233 to try to understand what actions are necessary to propagate the pypi release to conda-forge. This is typically an automatic process.

- As a temporary solution, I also uploaded it to my personal conda channel, which you can install using `conda install -c jmcarpenter2 swifter`. But that is NOT the official `conda-forge` channel and I would only recommend using it if absolutely necessary. Preferable would be to wait for conda-forge to update it on their official package channel.

**Comment by jmcarpenter2** [comment]
Wow sorry I didn't read the question closely.

@ggnicolau, to reproduce a conda install just find out what version of swifter you are running in conda (`conda list | grep swifter`) and use the following pip command
`pip install swifter==version`
e.g. `pip install swifter==1.1.2`

**Comment by ggnicolau** [comment]
Thank you, @jmcarpenter2 . I improvised something that worked. I've seen this thread was moving but I was waiting a bit to focus again and test. Yes, your last message answers my question, thank you. I will update my project with that.

**Comment by jmcarpenter2** [comment]
Thanks @ggnicolau !
