### ISSUE TITLE
error raised when applied on Dataset containing text,

### ISSUE THREAD

**Issue by Absolutorcinus** [jmcarpenter2/swifter#177]
I get this error whenever i try to apply swifter on my Dataset,
while for the following example it works:
```
#def add_squares(a,b):
#    return a**2+b**2
#df = pd.DataFrame({'X':np.random.randint(1000, size=100000),'Y':np.random.randint(1000, size=100000)})
#df ['add_sq']=df.swifter.apply(lambda row:add_squares(row.X,row.Y),axis=1)
```
**My code**
```
import swifter
import pandas as pd
import numpy as np
```

```
df = pd.read_csv('dataset.csv')
#function to return the length of the string
def letcnt(a):
    return len(a)

df['something'] = df['text'].swifter.apply(lambda x: letcnt(x))
```
Error:
-------------------------------------------------------

> Pandas Apply:   0%|          | 0/91388 [00:00<?, ?it/s]Traceback (most recent call last):
>   File "C:\Users\ii\PycharmProjects\pythonProject1\venv\lib\site-packages\swifter\swifter.py", line 258, in apply
>     & (sample_df.shape == tmp_df.shape),
> AttributeError: 'int' object has no attribute 'shape'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\ii\PycharmProjects\pythonProject1\sentiment_analisis\dataframe.py", line 11, in <module>
>     df['length_text'] = df['text'].swifter.apply(lambda x: letcnt(x))
>   File "C:\Users\ii\PycharmProjects\pythonProject1\venv\lib\site-packages\swifter\swifter.py", line 281, in apply
>     return self._obj.progress_apply(
>   File "C:\Users\ii\PycharmProjects\pythonProject1\venv\lib\site-packages\tqdm\std.py", line 754, in inner
>     func = df._is_builtin_func(func)
>   File "C:\Users\ii\PycharmProjects\pythonProject1\venv\lib\site-packages\pandas\core\generic.py", line 5478, in __getattr__
>     return object.__getattribute__(self, name)
> 
> AttributeError: 'Series' object has no attribute '_is_builtin_func'
> Pandas Apply:   0%|          | 0/91388 [00:00<?, ?it/s]
> 
> Process finished with exit code 1

_Originally posted by @Absolutorcinus in https://github.com/jmcarpenter2/swifter/issues/15#issuecomment-1077566041_

**Comment by jmcarpenter2** [comment]
Hey @Absolutorcinus, thank you very much for the extremely clear depiction of the issue.

The source of the issue is that the function you are using returns a single value when attempting to use the vectorized form (which swifter does first) and there wasn't handling to verify that it returns an array-like.

In pull request #179  i added handling for this scenario. In release 1.1.3 (which I will release soon) you will be able to use this function per expected.

Thank you again!

**Comment by YichaoOU** [comment]
Hello,

I'm still having this problem. version. 1.3.4

```
df = pd.DataFrame({'x': [1, 2, 3, 4], 'y': [5, 6, 7, 8]})
display( df.apply(lambda x:sum(x),axis=1))
display(df.swifter.apply(lambda x:sum(x),axis=1))

```
error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/.conda/envs/captureC/lib/python3.8/site-packages/swifter/swifter.py in apply(self, func, axis, raw, result_type, args, **kwds)
    426             with suppress_stdout_stderr_logging():
--> 427                 tmp_df = func(sample, *args, **kwds)
    428                 sample_df = sample.apply(func, axis=axis, raw=raw, result_type=result_type, args=args, **kwds)

<ipython-input-9-5ca00732a7a1> in <lambda>(x)
      2 display( df.apply(lambda x:sum(x),axis=1))
----> 3 display(df.swifter.apply(lambda x:sum(x),axis=1))

TypeError: unsupported operand type(s) for +: 'int' and 'str'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-9-5ca00732a7a1> in <module>
      1 df = pd.DataFrame({'x': [1, 2, 3, 4], 'y': [5, 6, 7, 8]})
      2 display( df.apply(lambda x:sum(x),axis=1))
----> 3 display(df.swifter.apply(lambda x:sum(x),axis=1))

~/.conda/envs/captureC/lib/python3.8/site-packages/swifter/swifter.py in apply(self, func, axis, raw, result_type, args, **kwds)
    449                     apply_func = self._obj.apply
    450 
--> 451                 return apply_func(func, axis=axis, raw=raw, result_type=result_type, args=args, **kwds)
    452 
    453     def _wrapped_applymap(self, func):

~/.conda/envs/captureC/lib/python3.8/site-packages/tqdm/std.py in inner(df, func, *args, **kwargs)
    779 
    780                 try:
--> 781                     func = df._is_builtin_func(func)
    782                 except TypeError:
    783                     pass

~/.conda/envs/captureC/lib/python3.8/site-packages/pandas/core/generic.py in __getattr__(self, name)
   5573         ):
   5574             return self[name]
-> 5575         return object.__getattribute__(self, name)
   5576 
   5577     def __setattr__(self, name: str, value) -> None:

AttributeError: 'DataFrame' object has no attribute '_is_builtin_func'
```
