### ISSUE TITLE
Feature Request: Compatibility with TQDM

### ISSUE THREAD

**Issue by lmusolff** [jmcarpenter2/swifter#18]
Any chance we could get compatibility with tqdm so we can watch progress of swifter apply operations? 

(Aside: thank you so much for swifter, it's really been a life-saver!)

**Comment by jmcarpenter2** [comment]
This is a fantastic idea!

I just uploaded version 0.240, which now utilizes TQDM to visualize the apply process. I added labels so you know which kind of apply is being used on your task (pandas or dask).

Please see the changelog for a full list of other changes in version 0.240.

Thank you very much for this valuable contribution to the package, @lmusolff!

**Comment by jmcarpenter2** [comment]
Please upgrade to version 0.242.
