### ISSUE TITLE
Swifter is not compatible with Pandas>=1.3.0 

### ISSUE THREAD

**Issue by zlyin** [jmcarpenter2/swifter#182]
Hello Jason,
I just came across another bug when dealing with a series of strings via Swifter. What I'm trying to do is as follows.

  ```python3
    >>> df = pd.DataFrame({"name" :[ "abdc_.jpg", "dafkda_.jpg", "kdajfdl_.jpg"]})
    >>> df
               name
    0     abdc_.jpg
    1   dafkda_.jpg
    2  kdajfdl_.jpg
    >>> df["name"].swifter.apply(lambda x : x.split("_")[0], axis=1)
  ```
  
It raises the following error:

  ```
Traceback (most recent call last):
  File "/data1/zlyin/miniconda3/lib/python3.8/site-packages/swifter/swifter.py", line 239, in apply
    tmp_df = func(sample, *args, **kwds)
  File "<stdin>", line 1, in <lambda>
  File "/data1/zlyin/miniconda3/lib/python3.8/site-packages/pandas/core/generic.py", line 5575, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'split'
```

This problem was caused by upgrading Pandas from `1.1.0` to `1.3.0` & `1.4.2`. I found 2 ways to walk around:
- 1st =  Downgrade pandas to the original version, the code worked.
- 2nd = Use `pandas.apply` function directly

I guess there might be something relevant to `Pandas.Index` settings because when I imported `swifter` after `import pandas(1.3.0 or 1.4.2)`, a future deprecated warning popped up, which said 

```
miniconda3/lib/python3.8/site-packages/dask/dataframe/utils.py:361: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  _numeric_index_types = (pd.Int64Index, pd.Float64Index, pd.UInt64Index)
```
 
Please have a look into this issue.
Thanks!

**Comment by jyk4100** [comment]
With pandas 1.4.3 and swifter 1.1.4 I can run your toy example. But I do get the following example,

```<>/miniconda3/envs/py38/lib/python3.8/site-packages/swifter/swifter.py:282: UserWarning: Axis keyword not necessary because applying on a Series.  warnings.warn("Axis keyword not necessary because applying on a Series.")```

AFAIK**, there is no parallel processing even if you were to use swifter here. 
**_I am not swifter nor dask developer but just another user_**
1. progress_bar.desc gives you "Pandas Apply"
2. idk if dask support type of string operation in your example (at least when I tried I couldn't get it do vectorized/parallel indexing)

**Comment by zlyin** [comment]
Hi @jyk4100, I think this bug is related to swifter's internal choice of picking "dask apply" or "pandas apply". But changing it to `some_df.my_col.apply(lambda x : my_func(x))` works well. 

I didn't spend more time digging in the source code. But my 2 cents here is playing swifter with non-numerical columns is very risky, especially if you want to apply a completex function to them.

**Comment by jmcarpenter2** [comment]
Hi all,

@zlyin , there is a parameter `allow_dask_on_strings` that you could use to provide parallel processing capability when processing a string. By default this was turned off because dask doesn't always improve performance for string processing. Please check the [docs](https://github.com/jmcarpenter2/swifter/blob/master/docs/documentation.md) for more information

You can use it as `df["name"].swifter.allow_dask_on_strings(enable=True).apply(lambda x: x.split("_")[0])`

FWIW I also tried your toy example using these versions of pandas and swifter and did not encounter the error. As such I am going to close this issue as the title is misleading.

**Comment by zlyin** [comment]
Hi Jason, 
  Great thanks for your help! I'll record your snippet for next time use. Thank you!
