### ISSUE TITLE
I find that if I replace the function arguments with lambda functions, the swifter  can speed up.

### ISSUE THREAD

**Issue by jaminmei** [jmcarpenter2/swifter#188]
After #187, I changed the function parameter in `apply` with lambda funvtion, then the swifter worked which completed the processing in about  8s. The screenshot is attached below.
![1658021855330(1)](https://user-images.githubusercontent.com/103319970/179380338-eec7c7f8-e755-4fd3-b9dc-040a5ff5af05.png)
Row 126 and Row 127 have been shown in #187. I tried the lambda function in Row 129, then the swifter worked. Additionally, I still remove the swifter in Row 129 which execution time is 35s which is close to Row 126 and Row 127.

**Comment by jmcarpenter2** [comment]
Closing this issue in favor of #190
