### ISSUE TITLE
Repeat the print outside the main function

### ISSUE THREAD

**Issue by jaminmei** [jmcarpenter2/swifter#189]
After #188, I got a bizarre situation during my test that I add a `print('para-test')` outside the main function which is shown below and I got 'para-test' many times when I run my code. Does this have anything to do with the use of the swifter?
![1658022946309](https://user-images.githubusercontent.com/103319970/179380842-8a892d1c-ae6d-494b-b9f4-5234e09baf3a.png)
![1658023328017](https://user-images.githubusercontent.com/103319970/179380857-076083ce-387b-45e5-90c6-a0d993c3ef7c.png)

**Comment by jmcarpenter2** [comment]
Hi @jaminmei , 

Could you please show the entire relevant code? If you run swifter outside of a function and you aren't using `if __name__ == "__main__"` then this sort of issue can happen. I believe there are some closed issues with the same problem

Thanks!
Jason

**Comment by jaminmei** [comment]
Hi @jmcarpenter2,

Thanks for your reply. Actually I run swifter in a function and `if __name__ == __main__` is also used. I would show more details and here are some snapshots.
I use swifter in function `traverse_one_csv()`.
![1658217197262](https://user-images.githubusercontent.com/103319970/179697230-9a3a3f52-1908-467c-aebd-764c56c4e7fe.png)
The function `main()` shows a data-cleaning pipeline for the particular data. 
![1658217516362](https://user-images.githubusercontent.com/103319970/179698361-1738a645-43fd-4702-8c66-fbdda3d30d5e.png)
And `print('para-test')` is added unintentionally. haha..., when I run my code, the output really bothers me. Maybe I miss some subtext about swifter.

**Comment by jmcarpenter2** [comment]
Interesting... I am wondering if the issue is occurring because of multiple invocations of `tqdm`? That is, `swifter` uses tqdm to produce the progress bar but you are also using tqdm for each chunk in your reader dataframe

**Comment by jaminmei** [comment]
Hi @jmcarpenter2, sorry for the late reply. I gave up tqdm and tried again, but unfortunately I got the same output. So I tried to debug my code, I added breakpoints on line 21 and line 122 where you could find on aforementioned snapshots, then I find that the 1st 'para-test' was printed before line 173, and the 2nd 'para-test' to 9th 'para-test' was printed orderly before the 1st 'Dask Apply', the rest was printed orderly before the 2nd 'Dask Apply'. The output snapshot is shown below.
![1658416716059(1)](https://user-images.githubusercontent.com/103319970/180250863-f2e8517e-b449-4ad4-ac7c-eed8bf002df6.png)
During this process, I found something interesting:
1. All 'para-test' was printed during the execution of swifter (line 121);
2. During the execution of swifter (line 121), the debugger would jump to `print('para-test')` (line 20);
3. The times of `print('para-test')` seems to be related to the number of my PC's cores.
So I guess that swifter process my dataset in each core of my PC and the lines outside the main function would be executed in each core, too.
