### ISSUE TITLE
Error when import library

### ISSUE THREAD

**Issue by Tranquangdai** [jmcarpenter2/swifter#2]
When I try to import swifter as: `import swifter`
I got this kind of error:

`File "/home/lap00379/venv/local/lib/python2.7/site-packages/swifter/swifter.py", line 27
    apply(myfunc, *args, **kwargs, axis=1, meta=meta).compute(get=get)
                                 ^
SyntaxError: invalid syntax`

I'm using Ubuntu 16.04  and Python 2.7

**Comment by jmcarpenter2** [comment]
Thanks for raising this issue! It was a minor issue with the ordering of key word arguments in python 2.7. I have resolved this issue now, and swifter should work for python 2.7. Happy applying!

**Comment by jmcarpenter2** [comment]
Hi @thesby,

It appears the answer to your question is version 0.153, but I strongly recommend updating to the latest version: 0.260 for added functionality and tweaks.

Thanks!
