### ISSUE TITLE
max_workers limited to 61

### ISSUE THREAD

**Issue by rileyg98** [jmcarpenter2/swifter#201]
Latest pypi version - I've just tried to use Swifter for the first time and it appears there's a max_workers limit of 61. Given swifters default of 2*cpu_core this is lower than a conceivable number - a 32-core Threadripper 3970x will go above this limit. 

Either setting a maximum of 61 when calculating the default, or expanding the max_workers limit would resolve this issue.

**Comment by rileyg98** [comment]
It would appear that this issue is related to cpython on Windows.

**Comment by jmcarpenter2** [comment]
Swifter defaults npartitions to 2*cpu_core, but you can control that parameter with `df.swifter.set_npartitions` or with the `set_defaults` functionality
