### ISSUE TITLE
Swifter With GroupBy - Crashing Python

### ISSUE THREAD

**Issue by SamPetherbridge** [jmcarpenter2/swifter#204]
Using Swifter with group by I am running into an error that is crashing the Python instance. Error below, please let me know if there is any more that will help getting to the bottom of this.

`2022-10-06 15:07:26,013	INFO worker.py:1518 -- Started a local Ray instance.
[failure_signal_handler.cc : 171] RAW: sigaltstack() failed with errno=1
/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '`

**Comment by jmcarpenter2** [comment]
This is concerning.. is this repeatedly an issue?

Can you share your environment details? OS, vCPUs, Memory, and versions of python, swifter, ray, etc?

Can you share any code you ran to cause this?

**Comment by SamPetherbridge** [comment]
Sometime has passed since I logged this and I have been unable to replicate. I will close this and reopen if I am able to replicate in future
