### ISSUE TITLE
 AttributeError: module 'pandas' has no attribute 'StringDtype'

### ISSUE THREAD

**Issue by wolaiye1010** [jmcarpenter2/swifter#205]
swifter                          1.3.4
pandas                           1.5.2

AttributeError                            Traceback (most recent call last)
<ipython-input-29-cdfb91fd62ad> in <module>
----> 1 import swifter
      2 import pandas as pd
      3 import numpy as np
      4 import geohash
      5 import subprocess

/usr/local/lib/python3.8/dist-packages/swifter/__init__.py in <module>
      3 import warnings
      4 from logging import config
----> 5 from .swifter import SeriesAccessor, DataFrameAccessor, set_defaults
      6 from .parallel_accessor import (
      7     register_parallel_dataframe_accessor,

/usr/local/lib/python3.8/dist-packages/swifter/swifter.py in <module>
      6 
      7 from abc import abstractmethod
----> 8 from dask import dataframe as dd
      9 from functools import partial
     10 from tqdm.auto import tqdm

/usr/local/lib/python3.8/dist-packages/dask/dataframe/__init__.py in <module>
      2     import dask.dataframe._pyarrow_compat
      3     from dask.base import compute
----> 4     from dask.dataframe import backends, dispatch, rolling
      5     from dask.dataframe.core import (
      6         DataFrame,

/usr/local/lib/python3.8/dist-packages/dask/dataframe/backends.py in <module>
     19 from dask.array.percentile import _percentile
     20 from dask.backends import CreationDispatch, DaskBackendEntrypoint
---> 21 from dask.dataframe.core import DataFrame, Index, Scalar, Series, _Frame
     22 from dask.dataframe.dispatch import (
     23     categorical_dtype_dispatch,

/usr/local/lib/python3.8/dist-packages/dask/dataframe/core.py in <module>
     33 from dask.blockwise import Blockwise, BlockwiseDep, BlockwiseDepDict, blockwise
     34 from dask.context import globalmethod
---> 35 from dask.dataframe import methods
     36 from dask.dataframe._compat import (
     37     PANDAS_GT_140,

/usr/local/lib/python3.8/dist-packages/dask/dataframe/methods.py in <module>
     20     union_categoricals,
     21 )
---> 22 from dask.dataframe.utils import is_dataframe_like, is_index_like, is_series_like
     23 
     24 # cuDF may try to import old dispatch functions

/usr/local/lib/python3.8/dist-packages/dask/dataframe/utils.py in <module>
     17 from dask.base import get_scheduler, is_dask_collection
     18 from dask.core import get_deps
---> 19 from dask.dataframe import (  # noqa: F401 register pandas extension types
     20     _dtypes,
     21     methods,

/usr/local/lib/python3.8/dist-packages/dask/dataframe/_dtypes.py in <module>
     14 
     15 
---> 16 @make_array_nonempty.register(pd.StringDtype)
     17 def _(dtype):
     18     return pd.array(["a", pd.NA], dtype=dtype)

/usr/local/lib/python3.8/dist-packages/pandas/__init__.py in __getattr__(name)
    212             "Int64Index": Int64Index,
    213             "UInt64Index": UInt64Index,
--> 214         }[name]
    215     elif name == "datetime":
    216         warnings.warn(

AttributeError: module 'pandas' has no attribute 'StringDtype'

**Comment by jmcarpenter2** [comment]
Hey @wolaiye1010,

I tried to recreate this issue on my own environment, but was not able to. Can you also write down your dask version? And then maybe try to `pip install -U dask[dataframe]` to upgrade it to a more recent version (if it is out of date)?

Thanks!

**Comment by wolaiye1010** [comment]
@jmcarpenter2 , think you! i have fix it by restart jupyter ，after install swifter it may be not valid immediately
