### ISSUE TITLE
Not compatible with pandas 1.5.3

### ISSUE THREAD

**Issue by dizhouwu** [jmcarpenter2/swifter#208]
Python: 3.10
swifter: 1.3.4

```
df = pd.DataFrame({'x': [1, 2, 3, 4], 'y': [5, 6, 7, 8]})
def my_sum(row):
    return row['x'] + row['y']
df[['x', 'y']].swifter.apply(my_sum)
```
```
KeyError                                  Traceback (most recent call last)
File /lib/python3.10/site-packages/pandas/core/indexes/base.py:3802, in Index.get_loc(self, key, method, tolerance)
   3801 try:
-> 3802     return self._engine.get_loc(casted_key)
   3803 except KeyError as err:
```

**Comment by jmcarpenter2** [comment]
Hi @dizhouwu, I think you are mis-using pandas here. When I try your code:
<img width="1263" alt="Screen Shot 2023-01-23 at 11 37 13 AM" src="https://user-images.githubusercontent.com/29585347/214133230-51e95a05-8621-4d45-94bb-9f5eccfbf2dc.png">

But when I add the `axis=1` flag to the apply:
<img width="645" alt="Screen Shot 2023-01-23 at 11 37 44 AM" src="https://user-images.githubusercontent.com/29585347/214133338-4a04c9c7-688d-469f-a36f-d069779c1cd6.png">
For further reading on pandas apply, you can see [here](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html)
