### ISSUE TITLE
Disable progress bar

### ISSUE THREAD

**Issue by shakebeforeuse** [jmcarpenter2/swifter#21]
Hello @jmcarpenter2!

Is there a way to disable output when using swifter.apply function? I'm using swifter inside a module to perform feature extraction and I rather not have any prints on screen.

Thank you!

**Comment by jmcarpenter2** [comment]
Hi @shakebeforeuse,

Sorry for the delay in my response. Please upgrade swifter to version 0.252. 

In this latest version, I have added support for disabling the progress bar by using the following syntax:
```df.swifter.progress_bar(False).apply(...)```

Now you can easily perform your swifter applies without the progress bar :)

Happy applying!

**Comment by shakebeforeuse** [comment]
Thank you for the fix!

Regards,
Manuel.
