### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by MemphisMeng** [jmcarpenter2/swifter#218]
I'm not sure if this was brought up before or not, I feel the readme isn't highly readable. Namely, line chars are ineligible without further context for a new user. Moreover, it seems that the declaration of 'my_func` isn't shown in README either.

Neither of them are magnificent issues but it could sabotage your potential user base. Say a coder wants to find your repo but your visualizations are convincing enough to let them try, it's a pity to lose a user in this way.

Suggested solutions:

1. include X axis and Y axis in all of your charts, especially their legends and titles.
2. Include `my_func`'s declaration.

**Comment by jmcarpenter2** [comment]
Hey @MemphisMeng , i am wondering if you are viewing github in dark mode? on my screen i see x and y axis.

![Screenshot 2023-07-20 at 9 11 42 AM](https://github.com/jmcarpenter2/swifter/assets/29585347/021fe0c2-88e1-4388-a5e6-9a2616d83f0f)

`my_func` takes up a lot of space.. but these are documented in [swifter_speed_comparison.ipynb](https://github.com/jmcarpenter2/swifter/blob/master/examples/swifter_speed_comparison.ipynb). I can provide a link if that's helpful

**Comment by jmcarpenter2** [comment]
Here is a PR that will make the docs more readable for dark-mode users
https://github.com/jmcarpenter2/swifter/pull/220

**Comment by jmcarpenter2** [comment]
#220  is merged, thanks for your input!
