### ISSUE TITLE
module pandas.api has no attribute extensions 

### ISSUE THREAD

**Issue by SaiNageswarS** [jmcarpenter2/swifter#24]
Importing swifter gives error:
module pandas.api has no attribute extensions

**Comment by jmcarpenter2** [comment]
Hi @SaiNageswarS,

Thanks for raising this issue. Older versions of pandas api did not have the extension necessary for swifter to work. Please upgrade pandas by calling `pip install -U pandas` before using swifter.

**Comment by bilbusra** [comment]
It didn't solve my problem, I tried both.
