### ISSUE TITLE
swifter apply for resample groups

### ISSUE THREAD

**Issue by harahu** [jmcarpenter2/swifter#26]
I've used swifter to speed up apply calls on DataFrames, but this isn't the only context apply is used in pandas. Would it be simple to implement for resample objects also?

See: [pandas.DataFrame.resample](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.resample.html)

Can we go from:
`series.resample('3T').apply(custom_resampler)`
to:
`series.resample('3T').swifter.apply(custom_resampler)`?

**Comment by jmcarpenter2** [comment]
Hi @harahu,

Thanks for proposing this feature. At the request of another user, I just added support for Rolling objects. I was able to do so because the underlying parallelization library, `dask`, has support for rolling object parallelized applies.

Unfortunately, while they do have support for creating Resampler objects in dask, those objects do not currently have an apply function that I can leverage. 

If/when the dask contributors add an apply function for resampler objects, then I will happily add that functionality to the package.

**Comment by jmcarpenter2** [comment]
@chrism2671 thanks!

I actually previously implemented groupby apply into swifter, but found that it was slower than a normal pandas groupby apply in many situations so I am currently leaving it out of the package.

**Comment by guyskk** [comment]
Dask queue (InterProcess Communication ) is slow and it's the bottleneck for groupby apply.
You should avoid any rows transfer between processes. I solved the problem (in another project) by write groupby partitions to disk, parallel read partition, do apply and write result to disk, finally read and concat the result.

**Comment by jmcarpenter2** [comment]
@guyskk that is a genius idea, thanks so much for your input. I do feel a bit concerned about forcefully writing to user's disks though, particularly if they are unaware of this.

**Comment by jmcarpenter2** [comment]
Hi @guyskk,

I have been trying to implement the groupby apply as you suggested but haven't seen any performance boost. Could you please share more details or even code on how you implemented this on your other project?

Thanks!

**Comment by guyskk** [comment]
HI @jmcarpenter2, there are 3 steps:
1. split dataset and write partitions into local disk (single thread)
2. read partition, process partition and write partition result (dask multiprocessing)
3. read results and concat, then write final result (single thread)

too small dataset(< 10k rows) will not have performance boost. when process large dataset(>1m rows) you will see step 1 and 3 are IO bound, step 2 is CPU bound, performance boost depends on how much IO and how heavy the CPU, in general 10x faster.

Here is the code: https://gist.github.com/guyskk/70eda8eefa8d1811248f5dd51a4edca8,
feel free to ask me any questions.

**Comment by jmcarpenter2** [comment]
Thanks @guyskk, this is awesome!

I'll take a look at the code in more depth soon and probably come back with questions then.

Much appreciated!

**Comment by noobymcnoob** [comment]
Same result here: the main slowdown when doing "parallel" groupby+apply is in data transfer.

**Comment by jmcarpenter2** [comment]
@harahu,

I am pleased to inform you that I was finally able to incorporate `resample` applies into `swifter` in version `0.296`.

To upgrade: `pip install swifter==0.296`

Syntax: `df.swifter.resample(...).apply(...)`

Thanks!
Jason

**Comment by harahu** [comment]
Good job!
