### ISSUE TITLE
Swifter Apply Rolling Objects

### ISSUE THREAD

**Issue by akaniklaus** [jmcarpenter2/swifter#27]
Hello,

Unable to use Swifter with rolling objects, an example use is as following. Thanks a lot in advance!

```
import swifter
log_returns.rolling(window=12, min_periods=1).swifter.apply(extract_labels)
```

I get the following error message:
```
  File "/anaconda2/lib/python2.7/site-packages/pandas/core/window.py", line 163, in __getattr__
    (type(self).__name__, attr))
AttributeError: 'Rolling' object has no attribute 'swifter'

```

**Comment by jmcarpenter2** [comment]
Hi @akaniklaus,

Thanks for raising this issue. I have now added support for rolling objects to the swifter package in version 0.260. 
`pip install swifter==0.260`

The usage remains idiomatic as follows:
`df.swifter.rolling(...).apply(...)`

For your example, that translates to:
`log_returns.swifter.rolling(window=12, min_periods=1).apply(extract_labels)`

This new feature is not extensively tested, but in my brief experimentation, it definitely increased speed.
Please give it a go, and feel free to reopen this issue if anything doesn't work properly.

Thanks again!
Jason

**Comment by akaniklaus** [comment]
Thanks a lot. Are expanding also supported?

**Comment by MrRobot2211** [comment]
Hi there excellent library.  Any news on supporting expanding ?
