### ISSUE TITLE
Progress Bar doesn't seem to be working

### ISSUE THREAD

**Issue by basilvetas** [jmcarpenter2/swifter#32]
Hi, I just installed swifter and I'm running something like:
```
df.swifter.apply(lambda x: custom_function(x), axis=1)
```
But the progress bar doesn't show up (there is no console output at all).  The documentation looks like `self._progress_bar` should be set to `True` by default, but I also tried:
```
df.swifter.progress_bar(enable=True).apply(lambda x: custom_function(x), axis=1)
 ```
In this case the progress bar still does not display.  I was initially running this in a Jupyter notebook, but also moved it over into a regular .py script run from terminal, and both scenarios there was no progress bar.  

Any ideas why this could be happening? Thanks.

**Comment by jmcarpenter2** [comment]
Thanks for raising this issue @basilvetas. I will look into this immediately. Could you note the version of swifter and pandas you have installed?

Thanks!

**Comment by jmcarpenter2** [comment]
@basilvetas please update to the latest version with `pip install swifter==0.272` and let me know if it's still broken for you. It appears to be working for me in jupyter notebooks. Thanks!

**Comment by jmcarpenter2** [comment]
Assuming the update resolved this issue. Closing for now, but please feel free to reopen if you are still experiencing this issue.

**Comment by VanDavv** [comment]
I'm still experiencing this issue
Version - swifter-0.283

I have dataframe with path locations, and have a function that, let's say, count it's length

```python
df['lengths'] = df.mystring.swifter.progress_bar(True).allow_dask_on_strings(enable=True).apply(extract_length)
```

Nothing shows up unfortunatelly

**Comment by jmcarpenter2** [comment]
Hi @VanDavv, can you tell me how long that function takes to run?

There is one scenario in which the progress bar doesn't appear and that's when the function is vectorizable. So if the function runs in a matter of milliseconds to maybe half a second it is probably just vectorized and there is no progress bar.

Alternatively, if you could provide the code for the function I can take a deeper dive into debugging this for you.

Thanks,
Jason

**Comment by VanDavv** [comment]
@jmcarpenter2 ok, so I'll go into more specific use case that I have.
Let's say we have a dataframe where one of the fields is an image location as a str. I want to add additional field with extracted facial encoding of this face. 

For this, I'm using specified function:

```python
def extract_encoding(image):
    result = next(iter(face_recognition.face_encodings(face_recognition.load_image_file(image))), None)
    return result
```

Each call of this function took about 83ms to finish

To add extra column to my dataframe I run the following code

```python
df['encoding'] = df.image.swifter.progress_bar(True).allow_dask_on_strings(enable=True).apply(extract_encoding)
```

What I came up with is to call `tqdm.progress(1)` in each call of `extract_encoding`, but this is obviously a workaround

**Comment by jmcarpenter2** [comment]
Hi @VanDavv,

Is the progress bar that appears a pandas apply progress bar or a dask progress bar?

I am wondering if the operation you are asking dask to perform isn't appropriate for dask dataframe. I believe you would be better off using `dask.bag.from_sequence(df.image).map(extract_encoding)`. Please check out the [docs](http://docs.dask.org/en/latest/bag.html).

Would love to hear back if that helps at least with speed of processing, if not the progress bar issue :)

**Comment by VanDavv** [comment]
Using dask seemed a bit an overhead to me, that's why I wanted to use swifter as it shown possibility for zero-config run.

I wanted to try dask during some task anyway anyway so I'll see if it would solve this issue
