### ISSUE TITLE
DataFrame Rolling Apply

### ISSUE THREAD

**Issue by huvar** [jmcarpenter2/swifter#37]
Hello,

I am having problem using rolling apply and swifter.
```
simulate_runs = lambda x: \
                    (np.array([np.random.choice(x,len(x)).sum() for i in range(try_cnt)])<0).sum()/try_cnt

ret_delta.swifter.rolling(-lookback).apply(simulate_runs)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-db392475e656>", line 1, in <module>
    ret_delta.swifter.rolling(-lookback).apply(simulate_runs)
  File "/home/hugo/.local/lib/python3.6/site-packages/swifter/swifter.py", line 53, in rolling
    return Rolling(self._obj, self._npartitions, self._dask_threshold, self._progress_bar, **kwds)
  File "/home/hugo/.local/lib/python3.6/site-packages/swifter/swifter.py", line 360, in __init__
    super(self).__init__(obj, npartitions, dask_threshold, progress_bar)
TypeError: super() argument 1 must be type, not Rolling
```
ret_delta is a Dataframe with only one column and the current versions in my system are:
pandas                        0.23.4      
swifter                       0.280 

Am I doing something wrong?

**Comment by jmcarpenter2** [comment]
Hi @huvar,

Sorry for the delay on this. I have been on holiday and will look into this shortly. Thanks for your patience!

-Jason

**Comment by jmcarpenter2** [comment]
Hi @huvar,

I had a small bug in the constructor for Rolling. Please upgrade to version 0.281 by calling `pip install swifter==0.281` and try again.

Please reopen the issue if this does not resolve your problem!

Thanks,
Jason
