### ISSUE TITLE
Required ipywidgets update

### ISSUE THREAD

**Issue by MichaelKarpe** [jmcarpenter2/swifter#43]
Hi @jmcarpenter2,

Many many thanks for the great tool you've developed!
I faced an issue when I tried to use swifter on a datetime pandas Series, with such a call:
```
data_frame['DATE_YEAR'] = data_frame['DATE'].swifter.apply(lambda x: x.year)
```

It raised a series of error, and particularly this one:
```
ImportError: IntProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
```

Therefore, as I wasn't in a Jupyter Notebook, I updated `ipywidgets` with `pip install ipywidgets` and it solved the issue. The installed ipywidgets version is 7.4.2.

I just added the installation of `ipywidgets>=7.4.2` in the setup.py file. Here is the pull request. Could you make the necessary checks and tell me if I have something to do? It's my first contribution on an open-source project, I don't know how it should happen... :smile: 

Best,
Michael

**Comment by jmcarpenter2** [comment]
Thanks so much for raising this issue @MichaelKarpe, but especially so for contributing to the package!

This issue is resolved in https://github.com/jmcarpenter2/swifter/pull/42
