### ISSUE TITLE
Not much performance difference between df.apply() and df.swifter.apply()

### ISSUE THREAD

**Issue by bhargav0795** [jmcarpenter2/swifter#44]
Firstly thanks for the amazing package!
I'm trying to calculate Levenshtein distance between two strings. I've created a random data frame with 2 million records. But I see that there isn't much difference in the performance of swifter and pd.apply(). Is there any way to improve it? I've attached screenshots below.

Dataframe creating
df = pd.DataFrame(data = {'x':['abrf eec']*2000000,'y':['dvd tettd']*2000000})
Levenshtein Distance library: from stringdist import rdlevenshtein as lev

Screenshot using swifter
![image](https://user-images.githubusercontent.com/25449723/54059071-d3d7aa80-41c5-11e9-8276-5511904ae85d.png)

Screenshot using pd.apply()
![image](https://user-images.githubusercontent.com/25449723/54059323-b6efa700-41c6-11e9-963a-2047c2f3f325.png)
 
@jmcarpenter2

**Comment by jmcarpenter2** [comment]
Hi @bhargav0795, 

The reason for the lack of difference in speed between `df.apply` and `df.swifter.apply` is that for your use-case it is explicitly the same. Referencing [#14](https://github.com/jmcarpenter2/swifter/issues/14), the underlying parallelization library `dask` is in fact slower to process strings than regular old pandas. The reason for this is not entirely clear but it seems to be that with all multiprocessing libraries the best we seem to be able to do is approximately equal pandas string processing speed.

If you want to try to test the dask utility of swifter on your problem, please use `df.swifter.allow_dask_on_strings(True).apply(lambda row: lev(row["x"], row["y"]), axis=1)`

I ran the above code and completed the processing in about 10 seconds. Please let me know if that works for you too!

**Comment by bhargav0795** [comment]
Wowa! That actually seems to work. It cut down the run time to 1 min. Thanks for the prompt response.

**Comment by jmcarpenter2** [comment]
You're welcome :) enjoy!
