### ISSUE TITLE
Jupyter notebook progress bar issues

### ISSUE THREAD

**Issue by Vozf** [jmcarpenter2/swifter#47]
If used inside jupyter notebook the standard tqdm progress bar is used instead of `tqdm_notebook`. Although if dask "backend" is used it utilizes the beautiful tqdm_notebook progress_bar. So it would be great if tqdm_notebook was always used when inside jupyter

**Comment by jmcarpenter2** [comment]
Hi @Vozf,

Thanks for raising this feature request!

I will be spending Saturday improving the `swifter` library, and will see if I can incorporate this.

Just to be clear, you are referring to the difference between the pandas tqdm progress bar and the dask tqdm progress bar?

Thanks,
Jason

**Comment by Vozf** [comment]
Simply answering your question - yes. But it is quite deeper than that.

There is tqdm.tqdm which has pandas support and works inside terminal. But progress bar are cli-style and are not really cool inside jupyter
There is tqdm.tqdm_notebook which has [buggy ](https://github.com/tqdm/tqdm/issues/419)pandas support and works inside jupyter. And it draws cool animated progress bar inside jupyter

So following the link above to have full support for jupyter and pandas we need
`from tqdm._tqdm_notebook import tqdm_notebook`
And probably `dask` developers use that one. Currently swifter uses tqdm.tqdm with cli-style progress bars. And it would be nice if it used tqdm._tqdm_notebook to draw cool charts in jupyter.

**Comment by jmcarpenter2** [comment]
Thanks for the details, I'll see if I can fix it up over the weekend 👍

**Comment by jmcarpenter2** [comment]
@Vozf - I had some spare time so I updated this in [#50](https://github.com/jmcarpenter2/swifter/pull/50) for swifter version 0.285. Turns out it was a simple fix using a different import from `tqdm.autonotebook`

Please `pip install swifter==0.285` or `pip install swifter -U` to upgrade to the latest version

Thanks again for raising this feature request. Let me know if you have any issues with it.
