### ISSUE TITLE
using always 4 cores 

### ISSUE THREAD

**Issue by mschmill** [jmcarpenter2/swifter#49]
I am using swifter 0.284 and am getting strange behavior. It is always using 4 cores -- no more, no less. Here is how I am using swifter:

```
dset = data.swifter.set_npartitions(args.partitions) 
j = dset.apply(lambda rt: rule.evaluate_named_rules(rc.PreparedText(rt.document,dept=rt.pdept)),axis=1)
```

The behavior is to use 4 cores regardless of whether args.partitions is 1,2,4,8, or 16. The machine it is running on has 8 vCPU. It is a GCP Compute Engine instance running Ubuntu. There is text processing within the lambda and I am trying to tune performance. Thanks!

edit: data size is between 10,000 and 300,000 rows per invocation

**Comment by jmcarpenter2** [comment]
Hi @mschmill,

Thanks for bringing this to my attention.

I tested out the set_npartitions functionality, and it appears to work correctly on my system.
But the aspect of this issue that really intrigues me is that you are getting any sort of parallelism at all, given that you are doing text processing. 

You can try adding `allow_dask_on_strings()` to your chain i.e. 
```dset = data.swifter.set_npartitions(args.partitions).allow_dask_on_strings()```

By default, when the input dataframe contains a string swifter will fall back to single core pandas apply. There is good reason for this, but we include `allow_dask_on_strings` for flexibility in case you want to override that functionality.

Please give that a go and let me know if that changes anything.

Thanks,
Jason

**Comment by mschmill** [comment]
After adding allow_dask_on_strings() I am seeing what looks like 1 process per partition, but each can use more than 100% CPU. Attached is a screenshot of htop with npartitions=3 which seems to indicate that usage could max out at 800% (full utilization). This particular trial is on MacOS which had been behaving roughly the same as the GCP VM also with 8 cores. 

Also for some reason the tqdm progress bar is creating an HTML (jupyter) progress bar from command line when I use .allow_dask_on_strings(). When I reran to verify this I see that I get one process with as much as 400% CPU according to top and htop regardless of the npartitions setting.

<img width="875" alt="Screen Shot 2019-04-15 at 9 38 16 AM" src="https://user-images.githubusercontent.com/14186571/56137239-5b9d9b00-5f62-11e9-80ea-53462edea038.png">

Setting npartitions to 8 and using the allow_dask_on_strings() setting I managed to see a speedup of 2x on one of my jobs, so that helps. It's still curious behavior, especially how dask performs on text. It seems like a use case that will be increasingly common so I hope there will be a way to speed it up!

Thanks for your help - let me know if there are other tests I can run to help.

**Comment by jmcarpenter2** [comment]
Hi @mschmill,

Thanks for confirming that the `allow_dask_on_strings` functionality resolved your problem. 

The HTML/CLI progress bar issue was resolved in version 0.285 (we are now on 0.286), so if you upgrade that should also be handled.

Thanks also for providing so much detail about your issue so I can more easily help with it.

The dask string processing issue is a known shortcoming, and a good deal of exploration has been done to find a way to do multiprocessing on text more efficiently. See [#14](https://github.com/jmcarpenter2/swifter/issues/14) for a discussion.

I'm not sure if I missed anything, but is there anything else I can do to help? 

Thanks,
Jason

**Comment by mschmill** [comment]
The only thing I don't understand is why it seems to use 4 cores when processing text without the `allow_dask_on_strings` flag set.

**Comment by jmcarpenter2** [comment]
Yeah that doesn't make any sense to me either. It should only be relying on 1 core in that case because it shouldn't even get to the point in swifter's logic where it is using dask...

**Comment by naisanzaa** [comment]
When using `allow_dask_on_strings` on a dtype of `object` and the content of the cell is `str`

I get this error:

```
TypeError: cannot pickle '_thread.lock' object
```
