### ISSUE TITLE
ZeroDivisionError: float division by zero` when using apply with small data frames

### ISSUE THREAD

**Issue by efviodo** [jmcarpenter2/swifter#56]
Dear,

Since I updated my swifter version from version 0.285 to version 0.287 I'm having problems with the _apply_ function, particularly in small pandas dataframe. Here is an example of how I am using the function:

`mydf.swifter.progress_bar(False).apply(lambda x: some_func(x))`

Here is the specific part of the output error that points to a swifter error:

` /lib/python3.6/site-packages/swifter/swifter.py", line 167, in apply
    est_apply_duration = samp_proc_est / self._SAMP_SIZE * self._obj.shape[0]
ZeroDivisionError: float division by zero`

Doing some diging on this Github repo I found that on [this](https://github.com/jmcarpenter2/swifter/commit/31901cc4c42fe92b8587b4baab13cf2154fb1745#diff-ad242a04628a718c8239819a28aefa41) commit some lines were changed and in particularly the _SAMP_SIZE class attribute was added. I have the felling that there is some error in class initialziation because when you call apply function with a data frame with less rows than 25000, _SAMP_SIZE are calculated as 0 value.

Any idea?

Thanks in advance.

**Comment by jmcarpenter2** [comment]
@efviodo thanks for flagging this. It is now fixed in version 0.288.

Please `pip install swifter==0.288` for the patch.
