### ISSUE TITLE
KeyError when applying a function

### ISSUE THREAD

**Issue by bilalghanem** [jmcarpenter2/swifter#60]
I have a pandas object called 'Twitter' has 4 columns:
['id', 'full_text', 'created_at', 'user']
'user' is a json object. 
When I apply the following code:

`tweets['userid'] = tweets['user'].apply(lambda user: user['id'])`
it works without any problem; here I extract the id of the tweet'w user and set it instead of the json object.

But when I add swifter, like:
`tweets['userid'] = tweets['user'].swifter.progress_bar(enable=True).apply(lambda user: user['id'])`

I get this error:

> Traceback (most recent call last):
>   File "C:\Program Files\JetBrains\PyCharm 2018.1.3\helpers\pydev\pydevd.py", line 1664, in <module>
>     main()
>   File "C:\Program Files\JetBrains\PyCharm 2018.1.3\helpers\pydev\pydevd.py", line 1658, in main
>     globals = debugger.run(setup['file'], None, None, is_module)
>   File "C:\Program Files\JetBrains\PyCharm 2018.1.3\helpers\pydev\pydevd.py", line 1068, in run
>     pydev_imports.execfile(file, globals, locals)  # execute the script
>   File "C:\Program Files\JetBrains\PyCharm 2018.1.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
>     exec(compile(contents+"\n", file, 'exec'), glob, loc)
>   File "..../main.py", line 12, in <module>
>     data.read_public_users()
>   File "....\data\data.py", line 314, in read_public_users
>     tweets['userid'] = tweets['user'].swifter.progress_bar(enable=True).apply(lambda user: user['id'])
>   File "C:\Python35\lib\site-packages\swifter\swifter.py", line 154, in apply
>     tmp_df = func(samp, *args, **kwds)
>   File "....\data\data.py", line 314, in <lambda>
>     tweets['userid'] = tweets['user'].swifter.progress_bar(enable=True).apply(lambda user: user['id'])
>   File "C:\Python35\lib\site-packages\pandas\core\series.py", line 868, in __getitem__
>     result = self.index.get_value(self, key)
>   File "C:\Python35\lib\site-packages\pandas\core\indexes\base.py", line 4375, in get_value
>     tz=getattr(series.dtype, 'tz', None))
>   File "pandas\_libs\index.pyx", line 81, in pandas._libs.index.IndexEngine.get_value
>   File "pandas\_libs\index.pyx", line 89, in pandas._libs.index.IndexEngine.get_value
>   File "pandas\_libs\index.pyx", line 129, in pandas._libs.index.IndexEngine.get_loc
>   File "pandas\_libs\index_class_helper.pxi", line 91, in pandas._libs.index.Int64Engine._check_type
> KeyError: 'id'

**Comment by jmcarpenter2** [comment]
Hi @bilalghanem,

Thanks for bringing this issue to my attention. This particular example is a very niche case where your pandas dataframe contains a column of dictionaries. While I don't necessarily recommend using pandas like this, I would like to support your use case. As such, in PR [#61](https://github.com/jmcarpenter2/swifter/pull/61), I've added the KeyError as an exception that we are catching in the logic of swifter.

Please `pip install swifter==0.289` to get the latest fix.

Thanks,
Jason
