### ISSUE TITLE
Integration with rpy2

### ISSUE THREAD

**Issue by jlevy44** [jmcarpenter2/swifter#62]
Hey there,

I'm aiming to run an rpy2 function using swifter (size of my data is 500 rows by 100k columns) (eg. https://github.com/dask/distributed/issues/2119). The python function calls rpy2 and operates on each row of the dataframe, outputting a numerical matrix (numpy) the same size as the row. I ran swifter apply, and tracked the usage of workers. It seems that only one worker is being fully utilized.

Later, when I specified a dask Client top attempt to circumvent the utilization issue, there was a segmentation fault.

What can I do to parallelize quickly without failure?

**Comment by jmcarpenter2** [comment]
Hi @jlevy44, 

Is there text data in the data frame? If so, then swifter defaults to regular pandas apply.

Try df.swifter.allow_dask_on_strings.apply(foo)

Let me know how that goes.
Thanks,
Jason

Try df.swifter.

**Comment by jlevy44** [comment]
No there were not any strings in the dataset. I ended up getting it to work just by hardcoding it with Dask.

**Comment by jlevy44** [comment]
I can close the issue, or we can continue the discussion to figure out where it may have been failing using swifter.

**Comment by jmcarpenter2** [comment]
@jlevy44 thanks for the follow-up.

Would you be willing to share the source code that worked? That would be really helpful in incorporating this into the library.

Thanks,
Jason
