### ISSUE TITLE
Progress Bars are not compatible with Pandas 0.25.0

### ISSUE THREAD

**Issue by wiseyoungbuck** [jmcarpenter2/swifter#65]
Pandas broke tqdm integration with version 0.25.0. And thusly, it seems to have broken swifter as well. 
see: https://github.com/tqdm/tqdm/issues/780

It still works with `.swifter.progress_bar(False)`

**Comment by jmcarpenter2** [comment]
Thanks for raising this issue @wiseyoungbuck.

One workaround is the aforementioned `df.swifter.progress_bar(False).apply(foo)`. Another temporary workaround is to not upgrade pandas to 0.25.0 until after this is fixed.

Unfortunately this is way upstream from `swifter`, so I don't have much power in fixing this for now. If the issues persists for awhile, I will look into alternative solutions e.g. implementing `progress_apply` myself. 

In the meantime, let's leave this issue open so others are aware.
