### ISSUE TITLE
Swifter + Pandas: script does not move on after using swifter + apply()

### ISSUE THREAD

**Issue by laimaretto** [jmcarpenter2/swifter#81]
I have a script that loads data from MySQL. After that a Pandas DataFrame is built. On it I do apply several `apply` methods.

When I run the script, without `swifter`, this is the ouput:

    Duration Job0_sql:  0.011724
    Duration Job0_df:   146.875376
    <class 'pandas.core.frame.DataFrame'>
    Int64Index: 3316 entries, 0 to 3315
    Data columns (total 57 columns):
    id                       3316 non-null int64
    routerName               3316 non-null object
    routerLabel              3306 non-null object

Meaning that the SQL query lasted 0.011724 seconds. The whole process on the DataFrame, 146.9 seconds. Finally I do print `df.info()`. It also generates some plots (.jpegs) from the data itself.

After using `df.swifter.apply(.)` along the code, the output shows something different, and does not move on...

    Duration Job0_sql:  0.012964
    Pandas Apply: 100%|██████████████████████████| 48516/48516 [00:57<00:00, 845.45it/s]
    Pandas Apply: 100%|██████████████████████████| 3316/3316 [00:00<00:00, 4463.01it/s]

I mean, after the `swifter` I'm not getting neither the time `Job0_df` nor the processing of the plots: the script just stops there after the progress bars.

Why is it that the code stops there? As per the [documentation][1], we only need to append the `swifter` keyword bebore the `apply` method.

Has anyone experienced something like this?

  [1]: https://github.com/jmcarpenter2/swifter

**Comment by jmcarpenter2** [comment]
Hi @laimaretto,

Thanks for raising this issue. I'm not quite sure what's going on, but if you provide some additional details perhaps we can debug this for you.

1. Can you please provide a sample of code of your usage of `swifter`? It would be extra helpful if you could additionally include the portion where you are timing the apply, as this piece is not a part of the output from `swifter`, though you expected it to be.
2. Can you please provide a snapshot of the data in the dataframe that you are running the applies on?

I think these two pieces of information (primarily #1) will be very helpful in debugging the issue for you.

Thanks,
Jason

**Comment by laimaretto** [comment]
Hello Jason,

First of all, thanks for this software. I've tried the examples (the one where you calculate the power of 2 of a column in a DF), and it is simply wonderfull the way processing speed is improved. Just Great!

Now, coming to my issue. 

# get startTime

`start = datetime.now()`

# Connect ty MySQL

As mentioned, my program connects to a MySQL database and gathers some info:

```
dbAddress = "192.168.0.1"
dbUser 	  = "user"	
dbPass 	  = "pass" 	
dbDb 	  = "db"
db        = pymysql.connect(dbAddress,dbUser,dbPass,dbDb)
query     = "select * from table;"

cur = db.cursor()
cur.execute(query)
routers = list(cur.fetchall())

end_job_0_sql = datetime.now()
print("Duration Job0_sql: ", (end_job_0_sql - start).total_seconds())
```

# Build DF

At this point I do have the results of the query in a list called `routers`. I turn that into a DataFrame and do some work on it. After I've worked on it, I calculate the time it took.

```
dfRouters = pd.DataFrame(routers)

[...work on the DF...]
	
end_job_0_df = datetime.now()
print("Duration Job0_df:     ", (end_job_0_df - end_job_0_sql).total_seconds())
print("Duration Total:       ", (end_job_0_df - start).total_seconds())
```

# Apply

For example, something I do on the DF is aplly several `apply` methods along it.

`dfRouters = dfRouters.apply(setFinalValue, axis=1)`

Now, the function `setFinalValue` analyses some values on some columns of the DF and generates further a new column with a `finalValue`. Here's the funtcion.

```
def setFinalValue(row):

	objName    = row['col1']
  	attrName     = row['col2']
	dict_value   = row['col3']
	uint_value   = row['col4']
	string_value = row['col5']
	finalValue   = 'N/A'

	if attrName in ['val1','val2','val3']:
		finalValue = dict_value
	elif attrName ==  'val4':
		finalValue = uint_value
	elif attrName in ['val5','val6']:
		finalValue = string_value
	else:
		finalValue = "N/A"

	row['finalValue'] = finalValue

	return row
```

But this is not the only `apply` that I do have. For example, I have this other `apply` that based on the day of the week I obtain the name of the day:

```
dfRouters['intTimeDay'] = dfRouters.apply(setDayOfWeek, axis=1)

def setDayOfWeek(row):

	try:
		dayNbr  = row['timeIntEnd'].weekday()
		dayName = row['timeIntEnd'].day_name()
		out     = str(dayNbr) + "_" + dayName[:3]
	except:
		print(row)
		quit()

	return out
```
Now, these are not the only `apply` that I do have. I have several: these two before are just an example of the type of work that I do.

# Final Thoughts

What I see is the following: 

a) If I do `df.apply(fncName, args=x)` I can get my program to run completely.
b) If I do `df.swifter.apply(fncName, args=x)` my program stops after the progress bars, which is my original question.

Why, after having applied the `swifter` before the `apply` method, I cannot get my script to complete execution?

Any idea will be hihgly appreciated. I'm very interested in seeing if `swifter` can help me in producing faster dataFrames.

**Comment by jmcarpenter2** [comment]
Hi @laimaretto,

Looking through your code you have a generic try/except clause, which results in running the `quit()` command. I am wondering if `swifter` is attempting to go through it's motions of attempting [vectorized apply, sample pandas applies, dask apply] and is receiving an exception from failed the vectorized apply, which is getting escalated to your exception handling.

To test this, can you try changing the except clause to the specific exception you are expecting? For example, it may be `except AttributeError:` instead of just `except:`

Let me know if that helps or if you have any additional questions.

Thanks,
Jason

**Comment by jmcarpenter2** [comment]
Archiving due to inactivity
