### ISSUE TITLE
threads

### ISSUE THREAD

**Issue by shimbalama** [jmcarpenter2/swifter#95]
Hi. After looking at you docs I can't see how to limit CPU usage. I work on a shared cluster with PBS and need to ensure my script doesn't exceed the number of CPUs I request. Is this possible?

Thanks,
Liam

**Comment by jmcarpenter2** [comment]
Hi @shimbalama ,

In the [docs](https://github.com/jmcarpenter2/swifter/blob/master/docs/documentation.md) page, there is a setting called `set_npartitions`, which defines how many chunks you want to split your dataframe into and perform the apply over. If you set this value to a number less than the number of CPUs on the shared cluster, then it should only use the number of partitions specified.

For example, the following code will run a swifter apply, using only 4 partitions (and therefore 4 should be CPUs).
```df.swifter.set_npartitions(4).apply(foo)```

Please give that a go and let me know if it worked for you :)

Thanks,
Jason
